accounts/urls.py
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView
)
from django.urls import path

from . import views
from .forms import UserPasswordReset, UserPasswordResetConfirm, UserChangePassword

urlpatterns = [
    path('profile/update/', views.UserProfileUpdateView.as_view(), name='profile_update'),
    path('profile/view/', views.UserProfileView.as_view(), name='profile'),
    path('address/view/', views.AddressView.as_view(), name='address'),
    path('orders/view/', views.OrdersView.as_view(), name='orders'),
    path('orders/view/<int:pk>/', views.OrderItemView.as_view(), name='order_item'),
    path('address/<int:pk>/update/', views.UpdateAddress.as_view(), name='update_address'),
    path('address/<int:pk>/default/', views.make_default, name='make_default'),
    path('address/<int:pk>/delete/', views.delete_address, name='delete_address'),
    path('reply/user/', views.AdminReplyView.as_view(), name='admin_reply'),
    path('reply/<int:pk>/', views.AdminReplyFullView.as_view(), name='admin_reply_full'),
    path('contacts/view/', views.SentView.as_view(), name='sent_view'),
    path('contacts/view/<int:pk>/', views.SentFullView.as_view(), name='sent_single_view'),

    #   user authentication urls
    path('', views.UserRegisterView.as_view(), name='register'),
    path('sign-in/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('sign-out/', views.UserLogout.as_view(), name='logout'),

    #   password reset urls
    path('password/reset/',
         PasswordResetView.as_view(template_name="accounts/reset_password.html",
                                   form_class=UserPasswordReset),
         name="password_reset"),

    path('password/reset/done/',
         PasswordResetDoneView.as_view(template_name="accounts/reset_password_done.html"),
         name="password_reset_done"),

    path('password/reset/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="accounts/reset_password_confirm.html",
                                          form_class=UserPasswordResetConfirm),
         name="password_reset_confirm"),

    path('password/reset/complete/',
         PasswordResetCompleteView.as_view(template_name="accounts/reset_password_complete.html"),
         name="password_reset_complete"),

    #   password change url
    path('password/change/', PasswordChangeView.as_view(
                            template_name="accounts/change_password.html",
                            form_class=UserChangePassword),
                            name="change_password")
]

armfamouzz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/<username>/', views.ContactView.as_view(), name='contact'),
    path('product/<int:pk>/', views.ProductView.as_view(), name='product_display'),
    path('sold-out/', views.sold_out_view, name='sold_out'),
    path('search/', views.search, name='search'),

    path('plus/<int:pk>/', views.plus_cart, name='plus_cart'),
    path('minus/<int:pk>/', views.minus_cart, name='minus_cart'),
    path('remove/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),

    path('cart/', views.CartView.as_view(), name='show_cart'),
    path('add-coupon/', views.AddCoupon.as_view(), name='add_coupon'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('request/refund/<int:pk>/', views.RequestRefundView.as_view(), name='request_refund'),

]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from core.models import Contact


GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Other'),
    ('D', 'Do not Specify'),
)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='D')

    def __str__(self):
        return self.user.username


class AdminReply(models.Model):
    receiver = models.ForeignKey(User, on_delete=models.CASCADE)
    reply_to = models.ForeignKey(Contact, on_delete=models.CASCADE)
    message = models.TextField()
    seen = models.BooleanField(default=False)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Reply to {self.receiver.username}"

core/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

TAG_CHOICES = (
    ('warning', 'New'),
    ('primary', 'Best Seller'),
    ('danger', 'Out Of stock'),
    ('info', 'Discounted'),

)

CATEGORY_CHOICES = (
    ('AW', 'African'),
    ('CW', 'Casual'),
    ('FW', 'Formal'),
    ('WW', 'Foreign')
)

REGION_CHOICES = (
    ('AS', 'Ashanti'),
    ('GA', 'Accra'),
    ('WR', 'Western'),
    ('OR', 'Oti'),
    ('NR', 'Northern'),
    ('UW', 'Upper West'),
    ('UE', 'Upper East')
)


class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICES)
    tag = models.CharField(max_length=15, choices=TAG_CHOICES)
    description = models.TextField()
    image = models.ImageField(upload_to='product_images')

    def __str__(self):
        return self.name


class OrderItem(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.item}"

    def get_final_price(self):
        if self.item.discount_price:
            return self.item.discount_price
        return self.item.price

    def get_total_price(self):
        return float(self.get_final_price() * self.quantity)

    def get_total(self):
        return self.item.price * self.quantity

    def get_discount_price(self):
        return self.item.discount_price * self.quantity

    def get_saved_amount(self):
        if self.item.discount_price:
            return self.get_total() - self.get_discount_price()


class Order(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    ref_code = models.CharField(unique=True, max_length=20)
    items = models.ManyToManyField(OrderItem)
    address = models.ForeignKey('Address', on_delete=models.SET_NULL, null=True, blank=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, null=True, blank=True)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order of {self.owner}"

    def get_final_cost(self):
        total = 0.00
        for item in self.items.all():
            total += item.get_total_price()
        return total

    def get_total_amount(self):
        total = self.get_final_cost()
        if self.coupon:
            total -= (self.coupon.coupon_percentage / 100) * total
        return total


class Address(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField()
    locality = models.CharField(max_length=200)
    street_name = models.CharField(max_length=200)
    region = models.CharField(max_length=2, choices=REGION_CHOICES)
    house_number = models.CharField(max_length=200)
    created = models.DateTimeField(default=timezone.now)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.locality

    class Meta:
        verbose_name_plural = 'Addresses'


class Coupon(models.Model):
    name = models.CharField(max_length=20)
    coupon_percentage = models.IntegerField()

    def __str__(self):
        return self.name


class Refund(models.Model):
    issuer = models.ForeignKey(User, on_delete=models.CASCADE)
    order_ref = models.CharField(max_length=30)
    reason = models.TextField()
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.issuer.username


class Contact(models.Model):
    contactor = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField(null=True, blank=True)
    subject = models.CharField(max_length=250, null=True, blank=True)
    message = models.TextField()
    date_sent = models.DateTimeField(default=timezone.now)
    sent = models.BooleanField(default=False)
    seen = models.BooleanField(default=False)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['-date_sent']

accounts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View

from core.models import Address, Order
from core.models import Contact
from .forms import (
    UserRegisterForm,
    UserForm,
    ProfileForm,
    AddressForm
)
from .models import Profile, AdminReply


@login_required(login_url='login')
def make_default(request, pk):
    user_addresses = Address.objects.filter(owner=request.user)
    curr_address = get_object_or_404(Address, id=pk)
    user_addresses.update(default=False)
    curr_address.default = True
    curr_address.save()
    return redirect('address')


@login_required(login_url='login')
def delete_address(request, pk):
    curr_address = get_object_or_404(Address, id=pk)
    curr_address.delete()
    return redirect('address')


class UserRegisterView(View):
    def get(self, request):
        form = UserRegisterForm()
        context = {
            'form': form,
        }
        return render(request, 'accounts/register.html', context)

    def post(self, request):
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('login')


class UserLogout(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'accounts/logout.html')

    def post(self, request):
        return LogoutView.as_view(next_page='login')(request)


class UserProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        profile = Profile.objects.filter(user=request.user).first()
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=profile)

        context = {
            'u_form': user_form,
            'p_form': profile_form,
        }
        return render(request, 'accounts/profile_update.html', context)

    def post(self, request):
        profile = Profile.objects.filter(user=request.user).first()
        user_form = UserForm(request.POST or None, instance=request.user)
        profile_form = ProfileForm(request.POST or None, instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('profile')

        context = {
            'u_form': user_form,
            'p_form': profile_form,
        }
        messages.error(request, 'Check the form correctly and make the necessary corrections!')
        return render(request, 'accounts/profile_update.html', context)


class UserProfileView(LoginRequiredMixin, View):
    def get(self, request):
        user_profile = Profile.objects.filter(user=request.user).first()

        context = {
            'profile': user_profile,
        }
        return render(request, 'accounts/profile.html', context)


class AddressView(LoginRequiredMixin, View):
    def get(self, request):
        address = Address.objects.filter(owner=request.user)

        context = {
            'addresses': address,
        }

        return render(request, 'accounts/address.html', context)


class UpdateAddress(LoginRequiredMixin, View):
    def get(self, request, pk):
        curr_address = get_object_or_404(Address, id=pk)
        form = AddressForm(instance=curr_address)

        context = {
            'form': form,
        }

        return render(request, 'accounts/update_address.html', context)

    def post(self, request, pk):
        curr_address = get_object_or_404(Address, id=pk)
        form = AddressForm(request.POST or None, instance=curr_address)

        if form.is_valid():
            updated_address = form.save(commit=False)
            updated_address.owner = request.user
            updated_address.email = request.user.email
            updated_address.save()
            return redirect('address')

        context = {
            'form': form,
        }

        return render(request, 'accounts/update_address.html', context)


class OrdersView(LoginRequiredMixin, View):
    def get(self, request):
        all_orders = Order.objects.filter(owner=request.user)

        context = {
            'orders': all_orders,
        }
        return render(request, 'accounts/orders.html', context)


class OrderItemView(LoginRequiredMixin, View):
    def get(self, request, pk):
        all_orders = Order.objects.filter(owner=request.user)
        curr_order = get_object_or_404(Order, id=pk)
        curr_order_item = curr_order.items.all()

        context = {
            'orders': all_orders,
            'curr_order': curr_order,
            'order_items': curr_order_item,
        }
        return render(request, 'accounts/orders.html', context)


class AdminReplyView(LoginRequiredMixin, View):
    def get(self, request):
        admin_message = AdminReply.objects.filter(receiver=request.user)

        context = {
            "reply_messages": admin_message,
            'active': 'primary',

        }

        return render(request, 'accounts/admin_reply.html', context)


class AdminReplyFullView(LoginRequiredMixin, View):
    def get(self, request, pk):
        curr_message = get_object_or_404(AdminReply, id=pk)
        admin_message = AdminReply.objects.filter(receiver=request.user)

        context = {
            'info': curr_message,
            'reply_messages': admin_message,
            'active': 'primary',

        }
        return render(request, 'accounts/admin_reply.html', context)

    def post(self, request, pk):
        curr_message = get_object_or_404(AdminReply, id=pk)
        admin_message = AdminReply.objects.filter(receiver=request.user)
        reply = request.POST.get('reply')

        contact = Contact()
        contact.contactor = request.user
        contact.email = request.user.email
        contact.subject = f'Reply to "{curr_message.reply_to.subject[:50].lower()}"'
        contact.message = reply
        contact.sent = True
        contact.save()

        curr_message.seen = True
        curr_message.save()

        return redirect('admin_reply')


class SentView(LoginRequiredMixin, View):
    def get(self, request):
        contact_message = Contact.objects.filter(contactor=request.user)

        context = {
            'contact_messages': contact_message,
            'is_active': 'primary',

        }
        return render(request, 'accounts/admin_reply.html', context)


class SentFullView(LoginRequiredMixin, View):
    def get(self, request, pk):
        curr_message = get_object_or_404(Contact, id=pk)
        contact_message = Contact.objects.filter(contactor=request.user)

        context = {
            'info': curr_message,
            'contact_messages': contact_message,
            'is_active': 'primary',
        }

        return render(request, 'accounts/admin_reply.html', context)

accounts/templates/accounts/address.html
{% extends 'core/base.html' %}


{% block title %}
    Address
{% endblock title %}



{% block content %}
    <div class="container my-5">
        <div class="row">
            <h3> Welcome <span class="text-capitalize"> {{ request.user }} </span></h3>
        
        <div class="col-sm-2 border-end">
            <ul class="list-unstyled">
                <li class="d-grid"><a href="{% url 'profile_update' %}" class="btn">
                <i class="fas fa-user-alt me-2"></i>Profile</a>
                </li>
                <li class="d-grid"><a href="{% url 'address' %}" class="btn btn-primary"><i class="fas fa-address-card me-2"></i>Address</a></li>
                <li class="d-grid"><a href="{% url 'orders' %}" class="btn"><i class="fas fa-dolly-flatbed me-2"></i>Orders</a>
                <li class="d-grid"><a href="{% url 'admin_reply' %}" class="btn">
                <i class="fas fa-envelope me-2"></i>Inbox</a>
                </li>
                </li>
            </ul>
        </div>
            <div class="col-sm-8 offset-sm-2">
                <div class="row">
                
                    {% for address in addresses %}
                        <div class="col-lg-6 col-md-6">
                            <div class="card text-center">
                                <div class="card-header">
                                    Address {{ forloop.counter }}
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title">Locality : 
                                    {{ address.locality }}</h5>
                                    
                                    <p class="card-text">Street Name : 
                                    {{ address.street_name }}
                                    </p>
                                    <p class="card-text">House Number : 
                                    {{ address.house_number }}
                                    </p>
                                    <p class="card-text">Region : 
                                    {{ address.get_region_display }} 
                                    </p>

                                    {% if address.default %}
                                        <div>
                                            <label for="Default">
                                                Default
                                                <input type="checkbox" name="Default" id="Default" checked>
                                            </label>
                                        </div>
                                    {% else %}
                                        <div>
                                            <a href="{% url 'make_default' address.id %}" class="btn btn-success mb-2">Make Default
                                            </a>
                                        </div>
                                    {% endif %}
                                    <a href="{% url 'update_address' address.id %}" class="btn btn-primary">Update</a>

                                    <a href="{% url 'delete_address' address.id %}" class="btn btn-danger">Delete</a>
                                </div>
                                <div class="card-footer text-body-secondary">
                                    Date Created : {{ address.created }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                    
                
            </div>
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/change_password.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    Change Password
{% endblock title %}






{% block content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h3 class='text-center'> Change Password  </h3>
            <fieldset>
                <form method='post' novalidate class='shadow p-5'>
                    {% csrf_token %}
                    {{ form | crispy }}
                    <input type="submit" value='Change' class='btn btn-info'>
                </form>
            </fieldset>
        </div>
    </div>
</div>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    Sign In
{% endblock title %}






{% block content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h3 class='text-center'> Sign In  </h3>
            <fieldset>
                <form method='post' novalidate class='shadow p-5'>
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-info"><i class="fas fa-unlock me-2"></i>Sign In</button>
                    <small class='text-center text-primary fw-fold text-dark '>
                        <a class='text-decoration-none' href="{% url 'password_reset' %}">
                            Forgot Password ? 
                        </a>
                    </small>
                    <br>
                    <small class='text-center text-primary fw-fold text-dark '>
                        Need An Account? 
                        <a class='text-decoration-none' href="{% url 'register' %}">Sign Up </a>
                    </small>
                </form>
            </fieldset>
        </div>
    </div>
</div>

{% endblock content %}
<

accounts/templates/accounts/logout.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    Logout
{% endblock title %}






{% block content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h3> Log Out Page </h3>
            <fieldset>
                <form method='post' class='shadow p-5'>
                    {% csrf_token %}
                    <h3> Are You Sure You Want To Sign Out ? </h3>
                    <input type="submit" value='Sign Out' class='btn btn-info'>
                    <a class='btn btn-secondary' href="{% url 'home' %}">Cancel</a>
                    
                </form>
            </fieldset>
        </div>
    </div>
</div>

{% endblock content %}

accounts/templates/accounts/orders.html
{% extends 'core/base.html' %}


{% block title %}
    Orders
{% endblock title %}



{% block content %}
    <div class="container my-5">
        <div class="row">
            <h3> Welcome <span class="text-capitalize"> {{ request.user }} </span></h3>
        
        <div class="col-lg-2 border-end">
            <ul class="list-unstyled">
                <li class="d-grid"><a href="{% url 'profile_update' %}" class="btn">
                <i class="fas fa-user-alt me-2"></i>Profile</a>
                </li>
                <li class="d-grid"><a href="{% url 'address' %}" class="btn"><i class="fas fa-address-card me-2"></i>Address</a></li>
                <li class="d-grid"><a href="{% url 'orders' %}" class="btn btn-primary"><i class="fas fa-dolly-flatbed me-2"></i>Orders</a></li>
                <li class="d-grid"><a href="{% url 'admin_reply' %}" class="btn">
                <i class="fas fa-envelope me-2"></i>Inbox</a>
                </li>
            </ul>
        </div>
            <div class="col-lg-8 offset-lg-2">
                <h1><center> Orders </center></h1>
                <hr>

                <div class="row">
                
                    <div class="col-md-6 col-lg-5 border-end">
                        <ul class="list-unstyled">
                            
                            {% for order in orders %}      
                                <li class="d-grid">
                                    <a href="{% url 'order_item' order.id %}" class="btn">
                                        <ul class='list-unstyled'>
                                            <li><h6>Ref Code : {{ order.ref_code }}</h6>
                                            </li>
                                            <li>Created : {{ order.created }}</li>
                                            <li>Refund Requested : {{ order.refund_requested }}</li>
                                            <li>Refund Granted : {{ order.refund_granted }}
                                            </li>
                                            <li><strong>Ordered : {{ order.ordered }}
                                            </strong></li>
                                            
                                            {% if order.coupon %}
                                                <li> {{ order.coupon }} - {{ order.coupon.coupon_percentage }}%</li>
                                                <li><strong>Cost : GHS{{ order.get_final_cost }}</strong>
                                                </li>
                                            {% endif %}
                                                
                                            <li><strong>TOTAL : GHS {{ order.get_total_amount }}</strong>
                                            </li>
                                        </ul>
                                        
                                            
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                        
                                
                    </div>
                    
                    <div class="col-md-6 col-lg-7">
                        <div class="row">
                        
                        {% if order_items %}
                            <h5><center>Ref Code : {{ curr_order.ref_code }}</center></h5>
                        {% endif %}
                        {%if curr_order.ordered and curr_order.refund_requested == False%}
                            <a href="{% url 'request_refund' curr_order.id %}" class="btn btn-sm btn-info">Request Refund</a>
                        {% endif %}
                            
                        
                            {% for order_item in order_items %}
                                <div class="col-lg-6 col-md-6 text-center">
                                    <p> {{ order_item.item.name }} </p>
                                    <p>Price : GHS {{ order_item.item.price }} </p>
                                    <p>Category :  {{ order_item.item.get_category_display }} </p>
                                    <p>Tag : {{ order_item.item.get_tag_display }} </p>
                                    <p> {{ order_item.item.description | truncatechars:20 }} </p>
                                <hr>
                                </div>
                            {% endfor %}
                                
                        </div>
                    </div>
                
                </div>
                    
                
            </div>
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Profile
{% endblock title %}



{% block content %}
    <div class="container my-5">
        <div class="row">
            <h3> Welcome <span class="text-capitalize"> {{ request.user }} </span></h3>
        
        <div class="col-sm-2 border-end">
            <ul class="list-unstyled">
                <li class="d-grid"><a href="{% url 'profile_update' %}" class="btn btn-primary"><i class="fas fa-user-alt me-2"></i>Profile</a></li>
                <li class="d-grid"><a href="{% url 'address' %}" class="btn"><i class="fas fa-address-card me-2"></i>Address</a>
                </li>
                <li class="d-grid"><a href="{% url 'orders' %}" class="btn"><i class="fas fa-dolly-flatbed me-2"></i>Orders</a>
                </li>
                <li class="d-grid"><a href="{% url 'admin_reply' %}" class="btn">
                <i class="fas fa-envelope me-2"></i>Inbox</a>
                </li>
            </ul>
        </div>
            <div class="col-sm-8 offset-sm-2">
                <ul class="list-unstyled">
                
                    <li><h3><center>Username : {{ request.user.username }}</li></center></h3>
                    <li><h3><center>Email : {{ request.user.email }}</li></center></h3>
                    <li><h3><center>Gender : {{ profile.get_gender_display }}</li></center></h3>
                </ul>
                <div>
                
                    <h3>
                        <center>User Bio</center>
                    </h3>
                    <p class="text-center"> {{ profile.bio }} </p>

                </div>
                <center>
                    <a class="btn btn-primary" href="{% url 'profile_update' %}">Update Profile</a>
                    <a class="btn btn-primary" href="{% url 'change_password' %}">
                    Change Password</a>
                </center>
            </div>
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/profile_update.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Profile
{% endblock title %}



{% block content %}
    <div class="container my-5">
        <div class="row">
            <h3> Welcome <span class="text-capitalize"> {{ request.user }} </span></h3>
        
        <div class="col-sm-2 border-end">
            <ul class="list-unstyled">
                <li class="d-grid"><a href="{% url 'profile_update' %}" class="btn btn-primary"><i class="fas fa-user-alt me-2"></i>Profile</a></li>
                <li class="d-grid"><a href="{% url 'address' %}" class="btn"><i class="fas fa-address-card me-2"></i>Address</a>
                </li>
                <li class="d-grid"><a href="{% url 'orders' %}" class="btn"><i class="fas fa-dolly-flatbed me-2"></i>Orders</a>
                </li>
                <li class="d-grid"><a href="{% url 'admin_reply' %}" class="btn">
                <i class="fas fa-envelope me-2"></i>Inbox</a>
                </li>
            </ul>
        </div>
    
            <div class="col-sm-8 offset-sm-2">
                <form method='post'>
                    {% csrf_token %}
                    {{ u_form | crispy }}
                    {{ p_form | crispy }}

                    <div class="col-12 mt-3">
                        <button class='btn btn-primary '><i class="fas fa-save me-2">
                        </i>Save
                        </button>
                        <a href="{% url 'profile' %}" class="btn btn-secondary">
                        <i class="fas fa-user-alt me-2"></i>Go to Profile</a>
                        <a class="btn btn-warning mt-1" href="{% url 'change_password' %}">
                    <i class="fas fa-edit me-2"></i>Change Password</a>
                    </div>
                </form>
            </div>   
        </div>
    </div>
{% endblock content %}